name: Build ccminer with MSVC

on:
  push:
    branches: [ Verus2.2, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: '17.0'  # Visual Studio 2022

      - name: Build ccminer.sln
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          msbuild ccminer.sln /p:Configuration=Release /p:Platform=x64 /m

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ccminer-build
          path: |
            Release\*

