name: Build with MSVC

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup MSVC Environment
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: '17.0' # Visual Studio 2022

      - name: Build project
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          msbuild path\to\your_project.sln /p:Configuration=Release /p:Platform=x64

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: path\to\your\project\Release\*
